#
# Prerequisites
#
# install VSCode extension: [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
# to use this tool
#

@host=localhost
@port=9090


### GET products endpoint
GET http://{{host}}:{{port}}/products HTTP/1.1


### POST add product endpoint
POST http://{{host}}:{{port}}/products HTTP/1.1
Content-Type: application/json

{
    "id":1,
    "name": "tea",
    "description": "a nice cup of tea",
    "price":100,
    "sku":"aaa-bbb-ccc"
}

### PUT add product endpoint
PUT http://{{host}}:{{port}}/products/1 HTTP/1.1
Content-Type: application/json

{
    "id":1,
    "name": "tea",
    "description": "a nice cup of shit",
    "price":100,
    "sku":"aaa-bbb-ccc"
}


### DELETE add product endpoint
DELETE http://{{host}}:{{port}}/products/1 HTTP/1.1

