#
# Prerequisites
#
# install VSCode extension: [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
# to use this tool
#

@host=localhost
@port=9090


### GET products endpoint
GET http://{{host}}:{{port}}/ HTTP/1.1


### POST add product endpoint
POST http://{{host}}:{{port}}/ HTTP/1.1
Content-Type: application/json

{
    "id":1,
    "name": "tea",
    "description": "a nice cup of tea"
}

### PUT add product endpoint
PUT http://{{host}}:{{port}}/1 HTTP/1.1
Content-Type: application/json

{
    "id":1,
    "name": "tea",
    "description": "a nice cup of tea"
}
